using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Cambiar1 : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void Furelise(){ //Fur Elise
        SceneManager.LoadScene("FurElise");
    }
    public void BS(){ //Cambia a la canci贸n Battle Symphony
        SceneManager.LoadScene("BattleSymphony");
    }
    public void ByTheWay(){ //Cambia a la canci贸n By The Way
        SceneManager.LoadScene("ByTheWay");
    }
    public void OtherSide(){ //Cambia a la canci贸n otherside
        SceneManager.LoadScene("OtherSide");
    }
    public void AmericanIdiot(){ //Cambia a la canci贸n American Idiot
        SceneManager.LoadScene("AmericanIdiot");
    }
}
